<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4d202e3f-93e8-4173-9f12-275f65471817</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CosmeticsShop.Application\CosmeticsShop.Application.csproj" />
    <ProjectReference Include="..\CosmeticsShop.Domain\CosmeticsShop.Domain.csproj" />
    <ProjectReference Include="..\CosmeticsShop.Infrastructure\CosmeticsShop.Infrastructure.csproj" />
  </ItemGroup>

</Project>
